#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.database.table
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LTW")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Study.Properties.Settings.Default.LTWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C01_id;
		
		private string _C02_firtsname;
		
		private string _C03_lastname;
		
		private System.Nullable<System.DateTime> _C04_birthday;
		
		private System.Nullable<bool> _C05_gender;
		
		private string _C06_phonenumber;
		
		private string _C07_address;
		
		private System.Data.Linq.Binary _C08_avatar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC01_idChanging(int value);
    partial void OnC01_idChanged();
    partial void OnC02_firtsnameChanging(string value);
    partial void OnC02_firtsnameChanged();
    partial void OnC03_lastnameChanging(string value);
    partial void OnC03_lastnameChanged();
    partial void OnC04_birthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnC04_birthdayChanged();
    partial void OnC05_genderChanging(System.Nullable<bool> value);
    partial void OnC05_genderChanged();
    partial void OnC06_phonenumberChanging(string value);
    partial void OnC06_phonenumberChanged();
    partial void OnC07_addressChanging(string value);
    partial void OnC07_addressChanged();
    partial void OnC08_avatarChanging(System.Data.Linq.Binary value);
    partial void OnC08_avatarChanged();
    #endregion
		
		public student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C01_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C01_id
		{
			get
			{
				return this._C01_id;
			}
			set
			{
				if ((this._C01_id != value))
				{
					this.OnC01_idChanging(value);
					this.SendPropertyChanging();
					this._C01_id = value;
					this.SendPropertyChanged("C01_id");
					this.OnC01_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C02_firtsname", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string C02_firtsname
		{
			get
			{
				return this._C02_firtsname;
			}
			set
			{
				if ((this._C02_firtsname != value))
				{
					this.OnC02_firtsnameChanging(value);
					this.SendPropertyChanging();
					this._C02_firtsname = value;
					this.SendPropertyChanged("C02_firtsname");
					this.OnC02_firtsnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C03_lastname", DbType="NChar(100)")]
		public string C03_lastname
		{
			get
			{
				return this._C03_lastname;
			}
			set
			{
				if ((this._C03_lastname != value))
				{
					this.OnC03_lastnameChanging(value);
					this.SendPropertyChanging();
					this._C03_lastname = value;
					this.SendPropertyChanged("C03_lastname");
					this.OnC03_lastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C04_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> C04_birthday
		{
			get
			{
				return this._C04_birthday;
			}
			set
			{
				if ((this._C04_birthday != value))
				{
					this.OnC04_birthdayChanging(value);
					this.SendPropertyChanging();
					this._C04_birthday = value;
					this.SendPropertyChanged("C04_birthday");
					this.OnC04_birthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C05_gender", DbType="Bit")]
		public System.Nullable<bool> C05_gender
		{
			get
			{
				return this._C05_gender;
			}
			set
			{
				if ((this._C05_gender != value))
				{
					this.OnC05_genderChanging(value);
					this.SendPropertyChanging();
					this._C05_gender = value;
					this.SendPropertyChanged("C05_gender");
					this.OnC05_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C06_phonenumber", DbType="NChar(10)")]
		public string C06_phonenumber
		{
			get
			{
				return this._C06_phonenumber;
			}
			set
			{
				if ((this._C06_phonenumber != value))
				{
					this.OnC06_phonenumberChanging(value);
					this.SendPropertyChanging();
					this._C06_phonenumber = value;
					this.SendPropertyChanged("C06_phonenumber");
					this.OnC06_phonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C07_address", DbType="NChar(200)")]
		public string C07_address
		{
			get
			{
				return this._C07_address;
			}
			set
			{
				if ((this._C07_address != value))
				{
					this.OnC07_addressChanging(value);
					this.SendPropertyChanging();
					this._C07_address = value;
					this.SendPropertyChanged("C07_address");
					this.OnC07_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C08_avatar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary C08_avatar
		{
			get
			{
				return this._C08_avatar;
			}
			set
			{
				if ((this._C08_avatar != value))
				{
					this.OnC08_avatarChanging(value);
					this.SendPropertyChanging();
					this._C08_avatar = value;
					this.SendPropertyChanged("C08_avatar");
					this.OnC08_avatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
